image: alpine/latest

packages:
  - nodejs
  - yarn

secrets:
  - e6f312d6-163a-40f3-924a-3d27c28f3af0 # ssh key to push to gh

# oauth: pages.sr.ht/PAGES:RW

environment:
  site: nu.031337.xyz

sources:
  - https://git.sr.ht/~robin_jadoul/nuboard

tasks:
  - deps: |
      cd nuboard
      yarn install
  - build: |
      cd nuboard
      yarn build
  # Can't use srht.site because CSP blocks the websockets for webrtc signaling
  # - package: |
      # cd nuboard/dist
      # tar -cvz . > ../../site.tar.gz
  # - upload: |
      # acurl -f https://pages.sr.ht/publish/$site -Fcontent=@site.tar.gz
  - update_mirror: |
      cd nuboard
      # guard we're on master
      git for-each-ref --format='%(objectname) %(refname:short)' refs/heads | awk "/^$(git rev-parse HEAD)/ {print \$2}" | grep master || exit 0
      git remote add gh git@github.com:RobinJadoul/nuboard.git
      GIT_SSH_COMMAND="ssh -oStrictHostKeyChecking=no" git push gh master
  - push: |
      cd nuboard/dist
      # guard we're on master
      git for-each-ref --format='%(objectname) %(refname:short)' refs/heads | awk "/^$(git rev-parse HEAD)/ {print \$2}" | grep master || exit 0
      echo "$site" > CNAME
      git init
      git remote add origin git@github.com:RobinJadoul/nuboard.git
      git add .
      git commit -m "build"
      GIT_SSH_COMMAND="ssh -oStrictHostKeyChecking=no" git push --force origin master:gh-pages

